package gui;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.table.DefaultTableModel;
import model.DbModel;
import model.Game;
import model.Member;

/**
 *
 * @author GAJDA NORBERT
 */
public class MainProgramDialog extends javax.swing.JDialog implements TableModelListener {

    DbModel model;
    DefaultTableModel dtmGames;
    DefaultTableModel dtmMembers;
    List<Game> games;
    List<Member> members;

    public MainProgramDialog(java.awt.Frame parent, DbModel model, String username) {
        super(parent, true);
        initComponents();
        this.model = model;
        parent.setVisible(false);
        setTitle("Video Game Rentals");
        setLocationRelativeTo(parent);

        lblWelcome.setText(username);

        refreshTable();
        
        //getting table model, and add listener for the later modifications in the table
        dtmGames = (DefaultTableModel) tblGames.getModel();
        dtmGames.addTableModelListener(this);
        dtmMembers = (DefaultTableModel) tblMembers.getModel();
        dtmMembers.addTableModelListener(this);

        //default view will always be the Games table
        tbtnVideoGamesActionPerformed(null);

        //for the tabs UI elements to be simple
        tbpGamesMembers.setUI(new BasicTabbedPaneUI());

    }

    // The content of this method is always regenerated by the Form Editor.
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblRentals = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tbpGamesMembers = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGames = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMembers = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tbtnMembers = new javax.swing.JToggleButton();
        tbtnVideoGames = new javax.swing.JToggleButton();
        btnManageMembers = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnManageGames = new javax.swing.JButton();
        btnManageEmployees = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));

        lblWelcome.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(204, 204, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRentals.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblRentals.setForeground(new java.awt.Color(204, 204, 204));
        lblRentals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRentals.setText("Video Game Rentals");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Logged in:");

        tbpGamesMembers.setBackground(new java.awt.Color(102, 102, 102));
        tbpGamesMembers.setForeground(new java.awt.Color(204, 204, 204));
        tbpGamesMembers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbpGamesMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbpGamesMembersMouseReleased(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        tblGames.setBackground(new java.awt.Color(102, 102, 102));
        tblGames.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblGames.setForeground(new java.awt.Color(204, 204, 204));
        tblGames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Genre", "Platform", "In Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGames.setFillsViewportHeight(true);
        tblGames.setGridColor(new java.awt.Color(102, 102, 102));
        tblGames.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblGames.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tblGames);
        if (tblGames.getColumnModel().getColumnCount() > 0) {
            tblGames.getColumnModel().getColumn(3).setHeaderValue("In ");
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbpGamesMembers.addTab("Video Games", jPanel6);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        tblMembers.setBackground(new java.awt.Color(102, 102, 102));
        tblMembers.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblMembers.setForeground(new java.awt.Color(204, 204, 204));
        tblMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMembers.setFillsViewportHeight(true);
        tblMembers.setGridColor(new java.awt.Color(102, 102, 102));
        tblMembers.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblMembers.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(tblMembers);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbpGamesMembers.addTab("Members", jPanel7);

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(204, 204, 204));
        btnLogout.setText("Log out");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbpGamesMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(lblRentals, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblRentals))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(tbpGamesMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\git\\JavaProject\\SwingVideoGameRentals\\src\\gui\\pictures\\playstation-icon.png")); // NOI18N

        tbtnMembers.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(tbtnMembers);
        tbtnMembers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbtnMembers.setForeground(new java.awt.Color(204, 204, 204));
        tbtnMembers.setText("Members");
        tbtnMembers.setBorder(null);
        tbtnMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnMembersActionPerformed(evt);
            }
        });

        tbtnVideoGames.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(tbtnVideoGames);
        tbtnVideoGames.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbtnVideoGames.setForeground(new java.awt.Color(204, 204, 204));
        tbtnVideoGames.setText("Video Games");
        tbtnVideoGames.setBorder(null);
        tbtnVideoGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnVideoGamesActionPerformed(evt);
            }
        });

        btnManageMembers.setBackground(new java.awt.Color(102, 102, 102));
        btnManageMembers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnManageMembers.setForeground(new java.awt.Color(204, 204, 204));
        btnManageMembers.setText("Manage Members");
        btnManageMembers.setBorder(null);
        btnManageMembers.setBorderPainted(false);
        btnManageMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMembersActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(102, 102, 102));
        btnExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(204, 204, 204));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnManageGames.setBackground(new java.awt.Color(102, 102, 102));
        btnManageGames.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnManageGames.setForeground(new java.awt.Color(204, 204, 204));
        btnManageGames.setText("Manage Games");
        btnManageGames.setBorder(null);
        btnManageGames.setBorderPainted(false);
        btnManageGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageGamesActionPerformed(evt);
            }
        });

        btnManageEmployees.setBackground(new java.awt.Color(102, 102, 102));
        btnManageEmployees.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnManageEmployees.setForeground(new java.awt.Color(204, 204, 204));
        btnManageEmployees.setText("Manage Employees");
        btnManageEmployees.setBorder(null);
        btnManageEmployees.setBorderPainted(false);
        btnManageEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtnMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtnVideoGames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageGames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addComponent(tbtnVideoGames, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(tbtnMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnManageGames, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnManageMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnManageEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tbtnMembers, tbtnVideoGames});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnVideoGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnVideoGamesActionPerformed

        tbtnVideoGames.setSelected(true);
        tbpGamesMembers.setSelectedIndex(0);

        dtmGames.getDataVector().clear();
        dtmGames.fireTableDataChanged();

        for (Game game : games) {
            Vector row = new Vector();

            row.add(game.getName());
            row.add(game.getGenre());
            row.add(game.getPlatform());
            if (game.getMembers_id() == 0) {
                row.add(true);
            } else {
                row.add(false);
            }

            dtmGames.addRow(row);
        }
    }//GEN-LAST:event_tbtnVideoGamesActionPerformed

    private void tbtnMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnMembersActionPerformed

        tbtnMembers.setSelected(true);
        tbpGamesMembers.setSelectedIndex(1);

        dtmMembers.getDataVector().clear();
        dtmMembers.fireTableDataChanged();

        for (Member member : members) {
            Vector row = new Vector();

            row.add(member.getName());
            row.add(member.getEmail());
            row.add(member.getPhone());

            dtmMembers.addRow(row);
        }
    }//GEN-LAST:event_tbtnMembersActionPerformed

    private void tbpGamesMembersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpGamesMembersMouseReleased
        if (tbpGamesMembers.getSelectedIndex() == 0) {
            tbtnVideoGamesActionPerformed(null);
        } else
            tbtnMembersActionPerformed(null);
    }//GEN-LAST:event_tbpGamesMembersMouseReleased
       
    private void btnManageMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMembersActionPerformed
        ManageMembersDialog mmd = new ManageMembersDialog(this, model);
        mmd.setVisible(true);
        refreshTable();
        tbpGamesMembersMouseReleased(null);
        
    }//GEN-LAST:event_btnManageMembersActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        try {
            model.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.toString(), "Database ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnManageGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageGamesActionPerformed
        ManageGamesDialog mgd = new ManageGamesDialog (this, model);
        mgd.setVisible(true);
        refreshTable();
        tbpGamesMembersMouseReleased(null);    }//GEN-LAST:event_btnManageGamesActionPerformed

    private void btnManageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeesActionPerformed
        ManageEmployeesDialog med = new ManageEmployeesDialog(this, model);
        med.setVisible(true);
        refreshTable();
        tbpGamesMembersMouseReleased(null);
    }//GEN-LAST:event_btnManageEmployeesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManageGames;
    private javax.swing.JButton btnManageMembers;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRentals;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblGames;
    private javax.swing.JTable tblMembers;
    private javax.swing.JTabbedPane tbpGamesMembers;
    private javax.swing.JToggleButton tbtnMembers;
    private javax.swing.JToggleButton tbtnVideoGames;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent arg0) {

    }

    private void refreshTable() {
        try {
            games = model.getAllVideoGames();
            members = model.getAllMembers();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.toString(), "Adatbázis hiba", JOptionPane.ERROR_MESSAGE);
        }
    }

}
